apiVersion: skaffold/v1beta11
kind: Config
build:
  local:
    useBuildkit: true
  artifacts:
    - image: kots-lint
      docker:
        dockerfile: Dockerfile.skaffold

profiles:
  - name: dev
    deploy:
      kustomize:
        path: kustomize/overlays/local